[package]
name = "learn-opengl"
version = "0.1.0"
authors = ["Brent Houghton <houghton.brent@gmail.com>"]

[dependencies]
cgmath="0.14.1"
gl="0.6.2"
glfw="0.15.0"
image="0.19.0"
tobj="0.1.6"
num="0.1.39"
rand="0.3.15"
