export default {
	WEBGL_CANVAS_ID: "drawing-canvas",
	FRAMES_PER_FPS_REPORT: 0,
	FOVY: 45,
	INITIAL_SCENE_TRANSLATION: { x: 0, y: 0, z: 0 },
	SCENE_TRANSLATION_STEP: 1,

	ENABLE_PYRAMID: true,

	ENABLE_CUBE: true,

	ENABLE_STARBURST: true,
	NUM_STARBURST_SPRITES: 50,

	ENABLE_RED_FLAME: true,
	ENABLE_PURPLE_FLAME: true,
	NUM_FLAME_SPRITES: 1000,
};
