export default {
	WEBGL_CANVAS_ID: "drawing-canvas",
	FRAMES_PER_FPS_REPORT: 100,
	FOVY: 45,
	INITIAL_SCENE_TRANSLATION: { x: 0, y: 0, z: 0 },
	SCENE_TRANSLATION_STEP: 1,
	NUM_STARBURST_SPRITES: 50,
};
